CREATE TABLE Users (Name VARCHAR(255) NOT NULL PRIMARY KEY, 
Password VARCHAR(255) NOT NULL, Email VARCHAR(255) NOT NULL);

CREATE TABLE Events (Title VARCHAR(255) NOT NULL PRIMARY KEY, 
Time DATETIME NOT NULL, Attendees VARCHAR(255) NOT NULL);