CREATE TABLE Users (Id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
Name VARCHAR(255) NOT NULL, Password VARCHAR(255) NOT NULL, Email VARCHAR(255) NOT NULL);
ALTER TABLE Users ADD CONSTRAINT PK_ID PRIMARY KEY (Id);

CREATE TABLE Events (Title VARCHAR(255) NOT NULL PRIMARY KEY, 
Time DATETIME NOT NULL, Attendees VARCHAR(255) NOT NULL);